CRITICAL - 2022-03-17 10:59:10 --> Unable to connect to the database.
#0 D:\xampp\htdocs\zerofees\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\zerofees\system\Controller.php(130): CodeIgniter\Database\BaseConnection->query('SET SESSION sql...')
#2 D:\xampp\htdocs\zerofees\app\Modules\Website\Controllers\BaseController.php(57): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#3 D:\xampp\htdocs\zerofees\system\CodeIgniter.php(899): App\Modules\Website\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\xampp\htdocs\zerofees\system\CodeIgniter.php(407): CodeIgniter\CodeIgniter->createController()
#5 D:\xampp\htdocs\zerofees\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\zerofees\index.php(64): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-03-17 11:08:29 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'D:\\xampp\\htdocs...', 2725, Array)
#1 D:\xampp\htdocs\tradebox\app\Modules\Website\Controllers\HomeController.php(2725): file_get_contents('https://min-api...', true)
#2 D:\xampp\htdocs\tradebox\system\CodeIgniter.php(926): App\Modules\Website\Controllers\HomeController->coingraphdata()
#3 D:\xampp\htdocs\tradebox\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Website\Controllers\HomeController))
#4 D:\xampp\htdocs\tradebox\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\tradebox\index.php(64): CodeIgniter\CodeIgniter->run()
#6 {main}
